services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file:
      - ./client/.env
    ports:
      - "3000:80" # Maps the React app from Nginx server to localhost:3000
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: "rosali"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "ewi"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
